<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13350" started-at="2019-08-22T23:52:07Z" finished-at="2019-08-22T23:52:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13350" started-at="2019-08-22T23:52:07Z" finished-at="2019-08-22T23:52:21Z">
      <class name="com.wbl.test.HomepageTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.wbl.test.HomepageTest@6f7fd0e6]" name="beforeSuite" is-config="true" duration-ms="17" started-at="2019-08-22T23:52:07Z" finished-at="2019-08-22T23:52:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.wbl.test.HomepageTest@6f7fd0e6]" name="beforeTest" is-config="true" duration-ms="13289" started-at="2019-08-22T23:52:07Z" finished-at="2019-08-22T23:52:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:com.wbl.test.HomepageTest@6f7fd0e6]" name="test1" duration-ms="19" started-at="2019-08-22T23:52:21Z" finished-at="2019-08-22T23:52:21Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at comwbl.pages.HomePage.getTitle(HomePage.java:36)
at com.wbl.test.HomepageTest.test1(HomepageTest.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.wbl.test.HomepageTest@6f7fd0e6]" name="afterSuite" is-config="true" duration-ms="2278" started-at="2019-08-22T23:52:21Z" finished-at="2019-08-22T23:52:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.wbl.test.HomepageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
